sudo: required
language: generic
matrix:
  include:
  - name: "Bionic beaver"
    dist: bionic
services:
  - docker
before-install:
  - docker pull wil3/gymfc:testing
install:
  - docker run -v $TRAVIS_BUILD_DIR:/tmp/gymfc "cd /tmp/gymfc && pip3 install ."

