sudo: required
language: generic
before-install:
  - sudo apt-get update
  # Install dart from source
  - git clone https://github.com/dartsim/dart.git /tmp/dart
  - cd /tmp/dart && git checkout v6.7.0
  - mkdir build && cd build
  - cmake ..
  - make -j4
  - make install 
  # Install boost dependency
  - sudo apt-get install -y libboost-all-dev
  # Install Gazebo from source http://gazebosim.org/tutorials?tut=install_from_source&cat=install
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add - && apt-get update
  - wget https://bitbucket.org/osrf/release-tools/raw/default/jenkins-scripts/lib/dependencies_archive.sh -O /tmp/dependencies.sh
  - /bin/bash -c "GAZEBO_MAJOR_VERSION=10 ROS_DISTRO=dummy source /tmp/dependencies.sh && echo \${BASE_DEPENDENCIES} \${GAZEBO_BASE_DEPENDENCIES} \${DART_DEPENDENCIES} | tr -d '\\' | xargs apt-get -y install"
  - hg clone https://bitbucket.org/osrf/gazebo /tmp/gazebo
  - cd /tmp/gazebo
  - hg up gazebo10_10.1.0
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/home/$USER/local ../
  - make -j4
  - make install

install:
  - pip install .
